DebugDrawVar("hp")
DebugDrawVar("wood")
DebugDrawVar("amber")
DebugDrawVar("buddies", array_length(crew.oBuddy) + instance_number(oBuddy))
DebugDrawVar("archers", array_length(crew.oArcherBuddy) + instance_number(oArcherBuddy))
DebugDrawVar("on_board_shooters", $"{on_board_shooters}/{on_board_shooters_max}")
DebugDrawVar("", "")
