var w = surface_get_width(application_surface)
var h = surface_get_height(application_surface)
DebugDrawVar("app surf", $"{w} {h}")
DebugDrawVar("window", $"{window_get_width()} {window_get_height()}")
DebugDrawVar("view", $"{CamW()} {CamH()}")
DebugDrawVar("gui", $"{display_get_gui_width()} {display_get_gui_height()}")
